### ISSUE TITLE
Create node module?

### ISSUE THREAD

**Issue by CodeLuca** [kleampa/not-paid#11]
I dont know how to copy paste code very well. please make node module with tutorial thx xoxoxo

**Comment by max-scopp** [comment]
Who buys domains from namecheap
![09857638](https://user-images.githubusercontent.com/11851540/52363617-652af400-2a43-11e9-9d92-cdbb18dbc182.jpg)

**Comment by CodeLuca** [comment]
> Who buys domains from namecheap
> ![09857638](https://user-images.githubusercontent.com/11851540/52363617-652af400-2a43-11e9-9d92-cdbb18dbc182.jpg)

> "Sleepy but highly passionate and **efficient Developer**"
> Spends time doing whois lookups on random people's old domain names....

**Comment by max-scopp** [comment]
Yes handsome dude dis troll

**Comment by max-scopp** [comment]
Dont close your arms, that makes them feel uncomfortable
I put them behind me

**Comment by spacemudd** [comment]
Have you tried turning it off and on?

**Comment by CodeLuca** [comment]
> Have you tried turning it off and on?

it keeps saying something about Java Runtime Environment?

**Comment by jonbp** [comment]
Obviously you need to download more RAM.

**Comment by tom-lord** [comment]
This doesn't have enough dependencies to qualify as a node module

**Comment by CodeLuca** [comment]
feelsbadman

**Comment by tubbo** [comment]
https://www.npmjs.com/package/delinquent
