### ISSUE TITLE
Code simplifications ;)

### ISSUE THREAD

**Issue by hevisko** [kleampa/not-paid#33]
`	var opacity = (days_late*100/days_deadline)/100;`

this could be simplified to:
`	var opacity = days_late/days_deadline;`

as
```
(days_late*100/days_deadline)/100
=> (days_late/days_deadline)*100/100
=> (days_late/days_deadline)
```

However, the opacity checks can be made even less and simpler as in:
```
	if(days > 0) { 
        // we only do the opacity if things are late, so opacity should always be <1
		var days_late = days_deadline-days;
		var opacity = (days_late >0) ? (days_late/days_deadline) : 0;
		document.getElementsByTagName("BODY")[0].style.opacity = opacity;
       }
```

**Comment by imlinus** [comment]
There is already a PR for that: https://github.com/kleampa/not-paid/pull/5

**Comment by hevisko** [comment]
:o
Missed that... but I still think mine is better/clearer than the math.max(math.min()) method ;)

Otherwise this code gave smiles on faces ;)
